@startuml newUserByTelegram
autonumber
skinparam {
    MaxMessageSize 820
    BoxPadding 10
    }
skinparam sequence {
    ParticipantPadding 30
    MessageAlign left
}
participant "api-telegram" as Api
participant "ms-telegram-adapter" as Tgm
participant "ms-subscription" as Sb


Api -> Tgm: Пользователь запросил \nсписок подписок
activate Api
activate Tgm
||20||
Tgm -> Sb: GET /subscriptions
activate Sb
||10||
Sb -> Tgm: Response 200 OK \n{SubscriptionsList}
deactivate Sb
Tgm -> Api: Response 200 OK
deactivate Api
deactivate Tgm
||30||
Api -> Tgm: Пользователь подписался на подписку
activate Api
activate Tgm
Tgm -> Sb: POST /subscriptions/{subscriptionId}/users
activate Sb
||80||
Sb -> Tgm: Response 204 OK
deactivate Sb
Tgm -> Api: Response 204 OK
deactivate Tgm
deactivate Api

@enduml