@startuml newUserByTelegram
autonumber
skinparam {
    MaxMessageSize 150
    BoxPadding 10
    }
skinparam sequence {
    ParticipantPadding 80
    MessageAlign left
}
participant "ms-user" as Usr order 70
participant "ms-telegram-adapter" as Tgm order 40
participant "api-telegram" as Api order 10

Api -> Tgm: У бота появился \nновый пользователь
activate Api
activate Tgm
||10||
Tgm -> Api: Response 200 OK
deactivate Api

Tgm -> Usr: POST /users  \n{UserCreateRequest}
activate Usr
||50||
Usr -> Usr:
note right :Создание нового \nпользователя

Usr -> Tgm: Response 200 OK \n{UserCreateResponse}
deactivate Tgm
deactivate Usr
||20||

@enduml