@startuml Subscription
autonumber
skinparam {
    MaxMessageSize 420
    BoxPadding 10   
    }
skinparam sequence {
    ParticipantPadding 30
    MessageAlign left
}

participant "ms-subscription" as Sb order 10
participant "ms-content" as Cn order 40
queue "kafka" as Kf order 150
participant "ms-telegram" as Tgm order 150
participant "api-telegram" as Api order 200

activate Sb
Sb -> Sb: Получение из таблицы subscription_user_info список пользователей для рассылки
||10||
group   Loop    [Для каждого пользователя]
    ||20||
    Sb -> Cn: GET/subscriptions/{subscriptionId}/contents?orderNumber={orderNumber}\nЗапрос контента
    activate Cn
    ||45||
    Cn -> Sb: Response 200 OK {ContentValue}
    ||10||
    deactivate Cn
    end
||45||

Sb -> Kf: ContentToSendPreparedEvent
deactivate Sb

||20||
activate Kf
Kf -> Tgm: read ContentToSendPreparedEvent

||30||
deactivate Kf
activate Tgm
group Loop [Для каждого отправленного сообщения \nформируем TelegramMassageSentEvent]
    Tgm -> Api: Отправляет контент пользователям Telegram
    activate Api
    Api -> Tgm: Response 200 OK
    deactivate Api
    end

Tgm -> Kf: TelegramMassageSentEvent
||20||
deactivate Tgm
activate Kf

Kf -> Sb: read TelegramMassageSentEvent
deactivate Kf
activate Sb
||50||
Sb -> Sb:
note right : Находим запись в subscription_user_info \nпо subscriptionId и telegramId. \nИнкрементируем order_number (+1)
||20||


@enduml