@startuml Subscription
autonumber
skinparam {
    MaxMessageSize 150
    BoxPadding 10   
    }
skinparam sequence {
    ParticipantPadding 30
    MessageAlign left
}

participant "ms-subscription" as Sb order 10
participant "ms-content" as Cn order 40
participant "ms-telegram" as Tgm order 60
participant "api-telegram" as Api order 80

activate Sb
Sb -> Sb: Получение из таблицы subscription_user_info список пользователей для рассылки
||10||
group   Loop    [Для каждого пользователя]
    ||20||
    Sb -> Cn: GET/subscriptions/{subscriptionId}/contents?orderNumber={orderNumber}\nЗапрос контента
    activate Cn
    ||45||
    Cn -> Sb: Response 200 OK {ContentValue}
    ||10||
    deactivate Cn
    end
||45||

Sb -> Tgm: POST/send \nОтправка контента для пользователей
activate Tgm
||20||
Tgm -> Api: Отправляет контент пользователям Telegram
activate Api
Api -> Tgm: Response 200 OK
deactivate Api
Tgm -> Sb: Response 204 OK
||20||
deactivate Sb
deactivate Tgm

@enduml