openapi: 3.0.0
info:
  title: Пользователи OpenAPI спецификация
  version: 0.0.1
servers:
    - url: https://62.109.27.168:9443/
      description: Dev server
paths:

components:
  schemas:
    TelegramMassageSentEvent:
      type: object
      required:
        - telegramId
        - subscriptionId
      properties:
          telegramId:
            type: string
            example: 343562780
          subscriptionId:
            type: string
            format: uuid
            example: 0e7932ef-6e23-4dc7-81cf-8e307fc13654


 
