openapi: 3.0.0
info:
  title: Пользователи OpenAPI спецификация
  version: 0.0.1
servers:
    - url: https://62.109.27.168:9443/
      description: Dev server
paths:
  /users:
    get:
      summary: Метод получения списка пользователей
      tags:
        - Users
      operationId: getAllusers
      responses:
        '200':
          description: Успешный ответ со списком пользователей
          content: 
            application/json: 
              schema:
                $ref: "#/components/schemas/UserValue"
        'default': 
          description: Все нестандартное
          content: 
            application/json:
              schema: 
                $ref: "#/components/schemas/Error"
    post:
      summary: Метод добавления нового пользователя
      tags:
        - Users
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserCreateRequest"
      responses:
        '200':
          description: Успешный ответ с одним пользователем
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserCreateResponse"
        'default':
          description: Все нестандартное
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    UserValue:
      type: object
      required:
        - telegramId
      properties:
        telegramId:
          type: string
          example: 34435262883635
        firstName:
          type: string
          example: Veronika
        lastName:
          type: string
          example: Bichik
        userName:
          type: string
          example: VBichik
        isBlocked:
          type: boolean
          example: false

    UsersList:
      type: object
      required:
        - userValueList
      properties:
        userValueList:
          type: array
          items:
            $ref: "#/components/schemas/UserValue"

    UserCreateRequest:
      type: object
      required:
        - firstName
        - lastName
        - telegramId
      properties:
        firstName:
          type: string
          example: Veronika
        lastName:
          type: string
          example: Bichik
        userName:
          type: string
          example: VBichik
        telegramId:
          type: string
          example: 34435262883635

    UserCreateResponse:
     allOf:
      - $ref: "#/components/schemas/UserValue"
      - type: object

    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
        message:
          type: string
